#!/usr/bin/env bash

model=speechio_kaldi
test_sets="MINI"
test_lang=zh

rm test_env
ln -s models/$model test_env
LEADERBOARD=$(readlink -f .) TEST_SETS="$test_sets" TEST_LANG=$test_lang  utils/benchmark.sh $model
