#!/usr/bin/env python3
import sys, os
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--type', choices=['model', 'dataset'], default='model')
    parser.add_argument('model_id', type=str, help='submission model id')
    parser.add_argument('model_dir', type=str, help='local submission model directory')
    args = parser.parse_args()
    print(args, file=sys.stderr)

    if args.type == 'model':
        model_info_file = os.path.join(args.model_dir, 'model.yaml')
        assert(os.path.isfile(model_info_file))
        sbi_bin_path = os.path.join(args.model_dir, 'SBI')
        assert(os.path.isfile(sbi_bin_path))
        docker_dir = os.path.join(args.model_dir, 'docker')
        assert(os.path.isdir(docker_dir))
        assert(os.path.isfile(os.path.join(docker_dir, 'Dockerfile')))
    else:
        pass

    assert os.path.isfile('oss'), "Can't find oss, please run utils/install_oss.sh"
    if not os.path.isfile('SAFEBOX/oss.cfg'):
        instructions_to_get_credential = (
            'You need credential to use the leaderboard:\n  '
            'Please send email with title "oss.cfg" to leaderboard@speechio.ai, '
            'and paste auto-replied content to SAFEBOX/oss.cfg'
        )
        print(instructions_to_get_credential, file=sys.stderr)
        sys.exit(-1)

    src = args.model_dir
    dst = os.path.join(F'oss://speechio-leaderboard/{args.type}-zoo', args.model_id) + '/'
    cmd = F'./oss -c SAFEBOX/oss.cfg cp -ur {src} {dst}'
    print(cmd, file=sys.stderr)
    os.system(cmd)
