# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.endpoint_update import EndpointUpdate  # noqa: E501
from swagger_client.rest import ApiException


class TestEndpointUpdate(unittest.TestCase):
    """EndpointUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointUpdate(self):
        """Test EndpointUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.endpoint_update.EndpointUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
