# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_web_hooks_api import CustomSpeechWebHooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomSpeechWebHooksApi(unittest.TestCase):
    """CustomSpeechWebHooksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_speech_web_hooks_api.CustomSpeechWebHooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_web_hooks_create(self):
        """Test case for web_hooks_create

        Creates a new web hook.  # noqa: E501
        """
        pass

    def test_web_hooks_delete(self):
        """Test case for web_hooks_delete

        Deletes the web hook identified by the given ID.  # noqa: E501
        """
        pass

    def test_web_hooks_get(self):
        """Test case for web_hooks_get

        Gets the web hook identified by the given ID.  # noqa: E501
        """
        pass

    def test_web_hooks_list(self):
        """Test case for web_hooks_list

        Gets the list of web hooks for the authenticated subscription.  # noqa: E501
        """
        pass

    def test_web_hooks_ping(self):
        """Test case for web_hooks_ping

        Sends a ping event to the registered URL.  # noqa: E501
        """
        pass

    def test_web_hooks_test(self):
        """Test case for web_hooks_test

        Sends a request for each registered event type to the registered URL.  # noqa: E501
        """
        pass

    def test_web_hooks_update(self):
        """Test case for web_hooks_update

        Updates the web hook identified by the given ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
