# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.file_links import FileLinks  # noqa: E501
from swagger_client.rest import ApiException


class TestFileLinks(unittest.TestCase):
    """FileLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileLinks(self):
        """Test FileLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.file_links.FileLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
