# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_projects_api import CustomSpeechProjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomSpeechProjectsApi(unittest.TestCase):
    """CustomSpeechProjectsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_speech_projects_api.CustomSpeechProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_projects_create(self):
        """Test case for projects_create

        Creates a new project.  # noqa: E501
        """
        pass

    def test_projects_delete(self):
        """Test case for projects_delete

        Deletes the project identified by the given ID.  # noqa: E501
        """
        pass

    def test_projects_get(self):
        """Test case for projects_get

        Gets the project identified by the given ID.  # noqa: E501
        """
        pass

    def test_projects_list(self):
        """Test case for projects_list

        Gets the list of projects for the authenticated subscription.  # noqa: E501
        """
        pass

    def test_projects_list_datasets(self):
        """Test case for projects_list_datasets

        Gets the list of datasets for specified project.  # noqa: E501
        """
        pass

    def test_projects_list_endpoints(self):
        """Test case for projects_list_endpoints

        Gets the list of endpoints for specified project.  # noqa: E501
        """
        pass

    def test_projects_list_evaluations(self):
        """Test case for projects_list_evaluations

        Gets the list of evaluations for specified project.  # noqa: E501
        """
        pass

    def test_projects_list_models(self):
        """Test case for projects_list_models

        Gets the list of models for specified project.  # noqa: E501
        """
        pass

    def test_projects_list_supported_locales(self):
        """Test case for projects_list_supported_locales

        Gets the list of supported locales.  # noqa: E501
        """
        pass

    def test_projects_list_transcriptions(self):
        """Test case for projects_list_transcriptions

        Gets the list of transcriptions for specified project.  # noqa: E501
        """
        pass

    def test_projects_update(self):
        """Test case for projects_update

        Updates the project identified by the given ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
