# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.project_links import ProjectLinks  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectLinks(unittest.TestCase):
    """ProjectLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectLinks(self):
        """Test ProjectLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.project_links.ProjectLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
