# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.commit_blocks_entry import CommitBlocksEntry  # noqa: E501
from swagger_client.rest import ApiException


class TestCommitBlocksEntry(unittest.TestCase):
    """CommitBlocksEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommitBlocksEntry(self):
        """Test CommitBlocksEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.commit_blocks_entry.CommitBlocksEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
