#!/usr/bin/env bash

if [ $# -ne 2 ]; then
  echo "recognize.sh wav.scp <working_dir>"
  exit 1;
fi

scp=$1
dir=$2
oss_scp=${scp}_oss
part_nums=10

# download ossutil64 tools
wget -O ossutil64 https://gosspublic.alicdn.com/ossutil/1.7.13/ossutil64
chmod 755 ossutil64

# upload wav to oss
./upload_wav.py $scp $oss_scp

# split test set 
awk -vf=${part_nums} -vl="`wc -l $oss_scp`" 'BEGIN{p=int(l/f);q=(l%f);for(n=1;n<=f;n++)a[n]=n*p+((n<=q)?++x:x)}{if(NR>a[i])i++;print > "'$oss_scp'."i}' $oss_scp
for((i=1;i<=${part_nums};i++));
  do
    nohup ./asr_sdk.py ${oss_scp}.${i} $dir/raw_rec.txt.${i} > $dir/sdk_log.${i} 2>&1 &
  done
wait

# merge parts and delete useless files
cat $dir/raw_rec.txt.* > $dir/raw_rec.txt
cat $dir/sdk_log.* > $dir/sdk_log
rm -rf $dir/sdk_log.*
rm -rf $dir/raw_rec.txt.*
rm -rf ${oss_scp}.*

# delete oss bucket
./del_oss_bucket.py
