#!/usr/bin/env bash

if [ $# -ne 2 ]; then
  echo "MBI wav.scp <working_dir>"
  exit 1;
fi

scp=$1
dir=$2

MODEL_DIR=`readlink -f assets`

export GLOG_logtostderr=1
export GLOG_v=2

decoder_main \
    --chunk_size -1 \
    --rescoring_weight 1.0 \
    --ctc_weight 0.5 \
    --wav_scp $scp \
    --model_path ${MODEL_DIR}/final.zip \
    --dict_path ${MODEL_DIR}/words.txt \
    --result $dir/raw_rec.txt 2>&1 | tee log.txt

