# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class BaseModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'BaseModelLinks',
        'properties': 'BaseModelProperties'
    }

    attribute_map = {
        'links': 'links',
        'properties': 'properties'
    }

    def __init__(self, links=None, properties=None, _configuration=None):  # noqa: E501
        """BaseModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._links = None
        self._properties = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if properties is not None:
            self.properties = properties

    @property
    def links(self):
        """Gets the links of this BaseModel.  # noqa: E501


        :return: The links of this BaseModel.  # noqa: E501
        :rtype: BaseModelLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this BaseModel.


        :param links: The links of this BaseModel.  # noqa: E501
        :type: BaseModelLinks
        """

        self._links = links

    @property
    def properties(self):
        """Gets the properties of this BaseModel.  # noqa: E501


        :return: The properties of this BaseModel.  # noqa: E501
        :rtype: BaseModelProperties
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this BaseModel.


        :param properties: The properties of this BaseModel.  # noqa: E501
        :type: BaseModelProperties
        """

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BaseModel):
            return True

        return self.to_dict() != other.to_dict()
