# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Endpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project': 'EntityReference',
        'links': 'EndpointLinks',
        'properties': 'EndpointProperties',
        '_self': 'str',
        'display_name': 'str',
        'description': 'str',
        'text': 'str',
        'model': 'EntityReference',
        'locale': 'str',
        'custom_properties': 'dict(str, str)',
        'last_action_date_time': 'datetime',
        'status': 'Status',
        'created_date_time': 'datetime'
    }

    attribute_map = {
        'project': 'project',
        'links': 'links',
        'properties': 'properties',
        '_self': 'self',
        'display_name': 'displayName',
        'description': 'description',
        'text': 'text',
        'model': 'model',
        'locale': 'locale',
        'custom_properties': 'customProperties',
        'last_action_date_time': 'lastActionDateTime',
        'status': 'status',
        'created_date_time': 'createdDateTime'
    }

    def __init__(self, project=None, links=None, properties=None, _self=None, display_name=None, description=None, text=None, model=None, locale=None, custom_properties=None, last_action_date_time=None, status=None, created_date_time=None, _configuration=None):  # noqa: E501
        """Endpoint - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._project = None
        self._links = None
        self._properties = None
        self.__self = None
        self._display_name = None
        self._description = None
        self._text = None
        self._model = None
        self._locale = None
        self._custom_properties = None
        self._last_action_date_time = None
        self._status = None
        self._created_date_time = None
        self.discriminator = None

        if project is not None:
            self.project = project
        if links is not None:
            self.links = links
        if properties is not None:
            self.properties = properties
        if _self is not None:
            self._self = _self
        self.display_name = display_name
        if description is not None:
            self.description = description
        if text is not None:
            self.text = text
        if model is not None:
            self.model = model
        self.locale = locale
        if custom_properties is not None:
            self.custom_properties = custom_properties
        if last_action_date_time is not None:
            self.last_action_date_time = last_action_date_time
        if status is not None:
            self.status = status
        if created_date_time is not None:
            self.created_date_time = created_date_time

    @property
    def project(self):
        """Gets the project of this Endpoint.  # noqa: E501


        :return: The project of this Endpoint.  # noqa: E501
        :rtype: EntityReference
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this Endpoint.


        :param project: The project of this Endpoint.  # noqa: E501
        :type: EntityReference
        """

        self._project = project

    @property
    def links(self):
        """Gets the links of this Endpoint.  # noqa: E501


        :return: The links of this Endpoint.  # noqa: E501
        :rtype: EndpointLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Endpoint.


        :param links: The links of this Endpoint.  # noqa: E501
        :type: EndpointLinks
        """

        self._links = links

    @property
    def properties(self):
        """Gets the properties of this Endpoint.  # noqa: E501


        :return: The properties of this Endpoint.  # noqa: E501
        :rtype: EndpointProperties
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this Endpoint.


        :param properties: The properties of this Endpoint.  # noqa: E501
        :type: EndpointProperties
        """

        self._properties = properties

    @property
    def _self(self):
        """Gets the _self of this Endpoint.  # noqa: E501

        The location of this entity.  # noqa: E501

        :return: The _self of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this Endpoint.

        The location of this entity.  # noqa: E501

        :param _self: The _self of this Endpoint.  # noqa: E501
        :type: str
        """

        self.__self = _self

    @property
    def display_name(self):
        """Gets the display_name of this Endpoint.  # noqa: E501

        The display name of the object.  # noqa: E501

        :return: The display_name of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this Endpoint.

        The display name of the object.  # noqa: E501

        :param display_name: The display_name of this Endpoint.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                display_name is not None and len(display_name) < 1):
            raise ValueError("Invalid value for `display_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this Endpoint.  # noqa: E501

        The description of the object.  # noqa: E501

        :return: The description of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Endpoint.

        The description of the object.  # noqa: E501

        :param description: The description of this Endpoint.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def text(self):
        """Gets the text of this Endpoint.  # noqa: E501

        The text used to adapt a language model for this endpoint.  # noqa: E501

        :return: The text of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Endpoint.

        The text used to adapt a language model for this endpoint.  # noqa: E501

        :param text: The text of this Endpoint.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def model(self):
        """Gets the model of this Endpoint.  # noqa: E501


        :return: The model of this Endpoint.  # noqa: E501
        :rtype: EntityReference
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this Endpoint.


        :param model: The model of this Endpoint.  # noqa: E501
        :type: EntityReference
        """

        self._model = model

    @property
    def locale(self):
        """Gets the locale of this Endpoint.  # noqa: E501

        The locale of the contained data.  # noqa: E501

        :return: The locale of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this Endpoint.

        The locale of the contained data.  # noqa: E501

        :param locale: The locale of this Endpoint.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and locale is None:
            raise ValueError("Invalid value for `locale`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                locale is not None and len(locale) < 1):
            raise ValueError("Invalid value for `locale`, length must be greater than or equal to `1`")  # noqa: E501

        self._locale = locale

    @property
    def custom_properties(self):
        """Gets the custom_properties of this Endpoint.  # noqa: E501

        The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.  # noqa: E501

        :return: The custom_properties of this Endpoint.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._custom_properties

    @custom_properties.setter
    def custom_properties(self, custom_properties):
        """Sets the custom_properties of this Endpoint.

        The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.  # noqa: E501

        :param custom_properties: The custom_properties of this Endpoint.  # noqa: E501
        :type: dict(str, str)
        """

        self._custom_properties = custom_properties

    @property
    def last_action_date_time(self):
        """Gets the last_action_date_time of this Endpoint.  # noqa: E501

        The time-stamp when the current status was entered.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :return: The last_action_date_time of this Endpoint.  # noqa: E501
        :rtype: datetime
        """
        return self._last_action_date_time

    @last_action_date_time.setter
    def last_action_date_time(self, last_action_date_time):
        """Sets the last_action_date_time of this Endpoint.

        The time-stamp when the current status was entered.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :param last_action_date_time: The last_action_date_time of this Endpoint.  # noqa: E501
        :type: datetime
        """

        self._last_action_date_time = last_action_date_time

    @property
    def status(self):
        """Gets the status of this Endpoint.  # noqa: E501


        :return: The status of this Endpoint.  # noqa: E501
        :rtype: Status
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Endpoint.


        :param status: The status of this Endpoint.  # noqa: E501
        :type: Status
        """

        self._status = status

    @property
    def created_date_time(self):
        """Gets the created_date_time of this Endpoint.  # noqa: E501

        The time-stamp when the object was created.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :return: The created_date_time of this Endpoint.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time):
        """Sets the created_date_time of this Endpoint.

        The time-stamp when the object was created.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :param created_date_time: The created_date_time of this Endpoint.  # noqa: E501
        :type: datetime
        """

        self._created_date_time = created_date_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Endpoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Endpoint):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Endpoint):
            return True

        return self.to_dict() != other.to_dict()
