# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SharedModelFeatures(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'supports_transcriptions': 'bool',
        'supports_endpoints': 'bool',
        'supports_transcriptions_on_speech_containers': 'bool'
    }

    attribute_map = {
        'supports_transcriptions': 'supportsTranscriptions',
        'supports_endpoints': 'supportsEndpoints',
        'supports_transcriptions_on_speech_containers': 'supportsTranscriptionsOnSpeechContainers'
    }

    def __init__(self, supports_transcriptions=None, supports_endpoints=None, supports_transcriptions_on_speech_containers=None, _configuration=None):  # noqa: E501
        """SharedModelFeatures - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._supports_transcriptions = None
        self._supports_endpoints = None
        self._supports_transcriptions_on_speech_containers = None
        self.discriminator = None

        if supports_transcriptions is not None:
            self.supports_transcriptions = supports_transcriptions
        if supports_endpoints is not None:
            self.supports_endpoints = supports_endpoints
        if supports_transcriptions_on_speech_containers is not None:
            self.supports_transcriptions_on_speech_containers = supports_transcriptions_on_speech_containers

    @property
    def supports_transcriptions(self):
        """Gets the supports_transcriptions of this SharedModelFeatures.  # noqa: E501

        A value indicating whether batch transcription is supported.  # noqa: E501

        :return: The supports_transcriptions of this SharedModelFeatures.  # noqa: E501
        :rtype: bool
        """
        return self._supports_transcriptions

    @supports_transcriptions.setter
    def supports_transcriptions(self, supports_transcriptions):
        """Sets the supports_transcriptions of this SharedModelFeatures.

        A value indicating whether batch transcription is supported.  # noqa: E501

        :param supports_transcriptions: The supports_transcriptions of this SharedModelFeatures.  # noqa: E501
        :type: bool
        """

        self._supports_transcriptions = supports_transcriptions

    @property
    def supports_endpoints(self):
        """Gets the supports_endpoints of this SharedModelFeatures.  # noqa: E501

        A value indicating whether creation of endpoints for live transcription is supported.  # noqa: E501

        :return: The supports_endpoints of this SharedModelFeatures.  # noqa: E501
        :rtype: bool
        """
        return self._supports_endpoints

    @supports_endpoints.setter
    def supports_endpoints(self, supports_endpoints):
        """Sets the supports_endpoints of this SharedModelFeatures.

        A value indicating whether creation of endpoints for live transcription is supported.  # noqa: E501

        :param supports_endpoints: The supports_endpoints of this SharedModelFeatures.  # noqa: E501
        :type: bool
        """

        self._supports_endpoints = supports_endpoints

    @property
    def supports_transcriptions_on_speech_containers(self):
        """Gets the supports_transcriptions_on_speech_containers of this SharedModelFeatures.  # noqa: E501

        A value indicating whether this model can be used for transcription on speech container. This feature can be added on existing models when it becomes usable on speech container.  # noqa: E501

        :return: The supports_transcriptions_on_speech_containers of this SharedModelFeatures.  # noqa: E501
        :rtype: bool
        """
        return self._supports_transcriptions_on_speech_containers

    @supports_transcriptions_on_speech_containers.setter
    def supports_transcriptions_on_speech_containers(self, supports_transcriptions_on_speech_containers):
        """Sets the supports_transcriptions_on_speech_containers of this SharedModelFeatures.

        A value indicating whether this model can be used for transcription on speech container. This feature can be added on existing models when it becomes usable on speech container.  # noqa: E501

        :param supports_transcriptions_on_speech_containers: The supports_transcriptions_on_speech_containers of this SharedModelFeatures.  # noqa: E501
        :type: bool
        """

        self._supports_transcriptions_on_speech_containers = supports_transcriptions_on_speech_containers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SharedModelFeatures, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SharedModelFeatures):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SharedModelFeatures):
            return True

        return self.to_dict() != other.to_dict()
