# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Transcription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'TranscriptionLinks',
        'properties': 'TranscriptionProperties',
        '_self': 'str',
        'model': 'EntityReference',
        'project': 'EntityReference',
        'dataset': 'EntityReference',
        'content_urls': 'list[str]',
        'content_container_url': 'str',
        'locale': 'str',
        'display_name': 'str',
        'description': 'str',
        'custom_properties': 'dict(str, str)',
        'last_action_date_time': 'datetime',
        'status': 'Status',
        'created_date_time': 'datetime'
    }

    attribute_map = {
        'links': 'links',
        'properties': 'properties',
        '_self': 'self',
        'model': 'model',
        'project': 'project',
        'dataset': 'dataset',
        'content_urls': 'contentUrls',
        'content_container_url': 'contentContainerUrl',
        'locale': 'locale',
        'display_name': 'displayName',
        'description': 'description',
        'custom_properties': 'customProperties',
        'last_action_date_time': 'lastActionDateTime',
        'status': 'status',
        'created_date_time': 'createdDateTime'
    }

    def __init__(self, links=None, properties=None, _self=None, model=None, project=None, dataset=None, content_urls=None, content_container_url=None, locale=None, display_name=None, description=None, custom_properties=None, last_action_date_time=None, status=None, created_date_time=None, _configuration=None):  # noqa: E501
        """Transcription - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._links = None
        self._properties = None
        self.__self = None
        self._model = None
        self._project = None
        self._dataset = None
        self._content_urls = None
        self._content_container_url = None
        self._locale = None
        self._display_name = None
        self._description = None
        self._custom_properties = None
        self._last_action_date_time = None
        self._status = None
        self._created_date_time = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if properties is not None:
            self.properties = properties
        if _self is not None:
            self._self = _self
        if model is not None:
            self.model = model
        if project is not None:
            self.project = project
        if dataset is not None:
            self.dataset = dataset
        if content_urls is not None:
            self.content_urls = content_urls
        if content_container_url is not None:
            self.content_container_url = content_container_url
        self.locale = locale
        self.display_name = display_name
        if description is not None:
            self.description = description
        if custom_properties is not None:
            self.custom_properties = custom_properties
        if last_action_date_time is not None:
            self.last_action_date_time = last_action_date_time
        if status is not None:
            self.status = status
        if created_date_time is not None:
            self.created_date_time = created_date_time

    @property
    def links(self):
        """Gets the links of this Transcription.  # noqa: E501


        :return: The links of this Transcription.  # noqa: E501
        :rtype: TranscriptionLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Transcription.


        :param links: The links of this Transcription.  # noqa: E501
        :type: TranscriptionLinks
        """

        self._links = links

    @property
    def properties(self):
        """Gets the properties of this Transcription.  # noqa: E501


        :return: The properties of this Transcription.  # noqa: E501
        :rtype: TranscriptionProperties
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this Transcription.


        :param properties: The properties of this Transcription.  # noqa: E501
        :type: TranscriptionProperties
        """

        self._properties = properties

    @property
    def _self(self):
        """Gets the _self of this Transcription.  # noqa: E501

        The location of this entity.  # noqa: E501

        :return: The _self of this Transcription.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this Transcription.

        The location of this entity.  # noqa: E501

        :param _self: The _self of this Transcription.  # noqa: E501
        :type: str
        """

        self.__self = _self

    @property
    def model(self):
        """Gets the model of this Transcription.  # noqa: E501


        :return: The model of this Transcription.  # noqa: E501
        :rtype: EntityReference
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this Transcription.


        :param model: The model of this Transcription.  # noqa: E501
        :type: EntityReference
        """

        self._model = model

    @property
    def project(self):
        """Gets the project of this Transcription.  # noqa: E501


        :return: The project of this Transcription.  # noqa: E501
        :rtype: EntityReference
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this Transcription.


        :param project: The project of this Transcription.  # noqa: E501
        :type: EntityReference
        """

        self._project = project

    @property
    def dataset(self):
        """Gets the dataset of this Transcription.  # noqa: E501


        :return: The dataset of this Transcription.  # noqa: E501
        :rtype: EntityReference
        """
        return self._dataset

    @dataset.setter
    def dataset(self, dataset):
        """Sets the dataset of this Transcription.


        :param dataset: The dataset of this Transcription.  # noqa: E501
        :type: EntityReference
        """

        self._dataset = dataset

    @property
    def content_urls(self):
        """Gets the content_urls of this Transcription.  # noqa: E501

        A list of content urls to get audio files to transcribe. Up to 1000 urls are allowed.  This property will not be returned in a response.  # noqa: E501

        :return: The content_urls of this Transcription.  # noqa: E501
        :rtype: list[str]
        """
        return self._content_urls

    @content_urls.setter
    def content_urls(self, content_urls):
        """Sets the content_urls of this Transcription.

        A list of content urls to get audio files to transcribe. Up to 1000 urls are allowed.  This property will not be returned in a response.  # noqa: E501

        :param content_urls: The content_urls of this Transcription.  # noqa: E501
        :type: list[str]
        """

        self._content_urls = content_urls

    @property
    def content_container_url(self):
        """Gets the content_container_url of this Transcription.  # noqa: E501

        A URL for an Azure blob container that contains the audio files. A container is allowed to have a maximum size of 5GB and a maximum number of 10000 blobs.  The maximum size for a blob is 2.5GB.  Container SAS should contain 'r' (read) and 'l' (list) permissions.  This property will not be returned in a response.  # noqa: E501

        :return: The content_container_url of this Transcription.  # noqa: E501
        :rtype: str
        """
        return self._content_container_url

    @content_container_url.setter
    def content_container_url(self, content_container_url):
        """Sets the content_container_url of this Transcription.

        A URL for an Azure blob container that contains the audio files. A container is allowed to have a maximum size of 5GB and a maximum number of 10000 blobs.  The maximum size for a blob is 2.5GB.  Container SAS should contain 'r' (read) and 'l' (list) permissions.  This property will not be returned in a response.  # noqa: E501

        :param content_container_url: The content_container_url of this Transcription.  # noqa: E501
        :type: str
        """

        self._content_container_url = content_container_url

    @property
    def locale(self):
        """Gets the locale of this Transcription.  # noqa: E501

        The locale of the contained data. If Language Identification is used, this locale is used to transcribe speech for which no language could be detected.  # noqa: E501

        :return: The locale of this Transcription.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this Transcription.

        The locale of the contained data. If Language Identification is used, this locale is used to transcribe speech for which no language could be detected.  # noqa: E501

        :param locale: The locale of this Transcription.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and locale is None:
            raise ValueError("Invalid value for `locale`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                locale is not None and len(locale) < 1):
            raise ValueError("Invalid value for `locale`, length must be greater than or equal to `1`")  # noqa: E501

        self._locale = locale

    @property
    def display_name(self):
        """Gets the display_name of this Transcription.  # noqa: E501

        The display name of the object.  # noqa: E501

        :return: The display_name of this Transcription.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this Transcription.

        The display name of the object.  # noqa: E501

        :param display_name: The display_name of this Transcription.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                display_name is not None and len(display_name) < 1):
            raise ValueError("Invalid value for `display_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this Transcription.  # noqa: E501

        The description of the object.  # noqa: E501

        :return: The description of this Transcription.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Transcription.

        The description of the object.  # noqa: E501

        :param description: The description of this Transcription.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def custom_properties(self):
        """Gets the custom_properties of this Transcription.  # noqa: E501

        The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.  # noqa: E501

        :return: The custom_properties of this Transcription.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._custom_properties

    @custom_properties.setter
    def custom_properties(self, custom_properties):
        """Sets the custom_properties of this Transcription.

        The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum  allowed value length is 256 characters and the count of allowed entries is 10.  # noqa: E501

        :param custom_properties: The custom_properties of this Transcription.  # noqa: E501
        :type: dict(str, str)
        """

        self._custom_properties = custom_properties

    @property
    def last_action_date_time(self):
        """Gets the last_action_date_time of this Transcription.  # noqa: E501

        The time-stamp when the current status was entered.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :return: The last_action_date_time of this Transcription.  # noqa: E501
        :rtype: datetime
        """
        return self._last_action_date_time

    @last_action_date_time.setter
    def last_action_date_time(self, last_action_date_time):
        """Sets the last_action_date_time of this Transcription.

        The time-stamp when the current status was entered.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :param last_action_date_time: The last_action_date_time of this Transcription.  # noqa: E501
        :type: datetime
        """

        self._last_action_date_time = last_action_date_time

    @property
    def status(self):
        """Gets the status of this Transcription.  # noqa: E501


        :return: The status of this Transcription.  # noqa: E501
        :rtype: Status
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Transcription.


        :param status: The status of this Transcription.  # noqa: E501
        :type: Status
        """

        self._status = status

    @property
    def created_date_time(self):
        """Gets the created_date_time of this Transcription.  # noqa: E501

        The time-stamp when the object was created.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :return: The created_date_time of this Transcription.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time):
        """Sets the created_date_time of this Transcription.

        The time-stamp when the object was created.  The time stamp is encoded as ISO 8601 date and time format  (\"YYYY-MM-DDThh:mm:ssZ\", see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).  # noqa: E501

        :param created_date_time: The created_date_time of this Transcription.  # noqa: E501
        :type: datetime
        """

        self._created_date_time = created_date_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Transcription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Transcription):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Transcription):
            return True

        return self.to_dict() != other.to_dict()
