# coding: utf-8

"""
    Speech Services API v3.1

    Speech Services API v3.1.  # noqa: E501

    OpenAPI spec version: v3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class WebHookLinks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ping': 'str',
        'test': 'str'
    }

    attribute_map = {
        'ping': 'ping',
        'test': 'test'
    }

    def __init__(self, ping=None, test=None, _configuration=None):  # noqa: E501
        """WebHookLinks - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ping = None
        self._test = None
        self.discriminator = None

        if ping is not None:
            self.ping = ping
        if test is not None:
            self.test = test

    @property
    def ping(self):
        """Gets the ping of this WebHookLinks.  # noqa: E501

        The URL that can be used to trigger the sending of a ping event to the registered URL of a web hook registration. See operation \"WebHooks_Ping\" for more details.  # noqa: E501

        :return: The ping of this WebHookLinks.  # noqa: E501
        :rtype: str
        """
        return self._ping

    @ping.setter
    def ping(self, ping):
        """Sets the ping of this WebHookLinks.

        The URL that can be used to trigger the sending of a ping event to the registered URL of a web hook registration. See operation \"WebHooks_Ping\" for more details.  # noqa: E501

        :param ping: The ping of this WebHookLinks.  # noqa: E501
        :type: str
        """

        self._ping = ping

    @property
    def test(self):
        """Gets the test of this WebHookLinks.  # noqa: E501

        The URL that can be used sending test events to the registered URL of a web hook registration. See operation \"WebHooks_Test\" for more details.  # noqa: E501

        :return: The test of this WebHookLinks.  # noqa: E501
        :rtype: str
        """
        return self._test

    @test.setter
    def test(self, test):
        """Sets the test of this WebHookLinks.

        The URL that can be used sending test events to the registered URL of a web hook registration. See operation \"WebHooks_Test\" for more details.  # noqa: E501

        :param test: The test of this WebHookLinks.  # noqa: E501
        :type: str
        """

        self._test = test

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebHookLinks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebHookLinks):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WebHookLinks):
            return True

        return self.to_dict() != other.to_dict()
